//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgroApplication
    {
        public int AgroApplicationId { get; set; }
        public System.Guid AgroApplicationGuid { get; set; }
        public int CropCycleId { get; set; }
        public int AgroInputId { get; set; }
        public System.DateTime AppliedAt { get; set; }
        public Nullable<decimal> DosePerHectare { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public string OperatorName { get; set; }
        public string WeatherNotes { get; set; }
        public Nullable<int> PreHarvestIntervalDays { get; set; }
    
        public virtual CropCycle CropCycle { get; set; }
        public virtual AgroInput AgroInput { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
