//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvestLot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HarvestLot()
        {
            this.InventoryMovements = new HashSet<InventoryMovement>();
            this.LabSamples = new HashSet<LabSample>();
            this.PackedProductLots = new HashSet<PackedProductLot>();
            this.QualityInspections = new HashSet<QualityInspection>();
            this.RecallTargets = new HashSet<RecallTarget>();
        }
    
        public int HarvestLotId { get; set; }
        public System.Guid HarvestLotGuid { get; set; }
        public int CropCycleId { get; set; }
        public string LotCode { get; set; }
        public System.DateTime HarvestDate { get; set; }
        public string ShiftCode { get; set; }
        public string PickerTeam { get; set; }
        public decimal GrossQuantity { get; set; }
        public int UnitOfMeasureId { get; set; }
        public int LotStatusId { get; set; }
        public string Notes { get; set; }
    
        public virtual CropCycle CropCycle { get; set; }
        public virtual LotStatu LotStatu { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMovement> InventoryMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabSample> LabSamples { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackedProductLot> PackedProductLots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityInspection> QualityInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecallTarget> RecallTargets { get; set; }
    }
}
