//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMovement
    {
        public int InventoryMovementId { get; set; }
        public System.Guid InventoryMovementGuid { get; set; }
        public int MovementTypeId { get; set; }
        public int HarvestLotId { get; set; }
        public System.DateTime OccurredAt { get; set; }
        public Nullable<int> FromStorageBinId { get; set; }
        public Nullable<int> ToStorageBinId { get; set; }
        public decimal Quantity { get; set; }
        public int UnitOfMeasureId { get; set; }
        public string Reference { get; set; }
        public string Notes { get; set; }
    
        public virtual HarvestLot HarvestLot { get; set; }
        public virtual StorageBin StorageBin { get; set; }
        public virtual StorageBin StorageBin1 { get; set; }
        public virtual InventoryMovementType InventoryMovementType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
