//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class IrrigationEvent
    {
        public int IrrigationEventId { get; set; }
        public System.Guid IrrigationEventGuid { get; set; }
        public int CropCycleId { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public Nullable<decimal> WaterVolume { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public string Notes { get; set; }
    
        public virtual CropCycle CropCycle { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
