//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabResult
    {
        public int LabResultId { get; set; }
        public System.Guid LabResultGuid { get; set; }
        public int LabSampleId { get; set; }
        public int LabTestTypeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> MeasuredValue { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public Nullable<decimal> LimitValue { get; set; }
        public Nullable<System.DateTime> ReportedAt { get; set; }
        public string LaboratoryName { get; set; }
        public string CertificateNo { get; set; }
        public string Notes { get; set; }
    
        public virtual LabSample LabSample { get; set; }
        public virtual LabResultStatu LabResultStatu { get; set; }
        public virtual LabTestType LabTestType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
