//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackedProductLot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackedProductLot()
        {
            this.PalletItems = new HashSet<PalletItem>();
            this.RecallTargets = new HashSet<RecallTarget>();
            this.ShipmentItems = new HashSet<ShipmentItem>();
        }
    
        public int PackedProductLotId { get; set; }
        public System.Guid PackedProductLotGuid { get; set; }
        public int PackingRunId { get; set; }
        public int SourceHarvestLotId { get; set; }
        public string PackedLotCode { get; set; }
        public int PackagingTypeId { get; set; }
        public decimal NetQuantity { get; set; }
        public int UnitOfMeasureId { get; set; }
        public Nullable<int> QualityGradeId { get; set; }
        public System.DateTime PackedAt { get; set; }
        public Nullable<System.DateTime> BestBeforeDate { get; set; }
        public string LabelTemplate { get; set; }
    
        public virtual HarvestLot HarvestLot { get; set; }
        public virtual PackagingType PackagingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletItem> PalletItems { get; set; }
        public virtual QualityGrade QualityGrade { get; set; }
        public virtual PackingRun PackingRun { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecallTarget> RecallTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItem> ShipmentItems { get; set; }
    }
}
