//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentItem
    {
        public int ShipmentItemId { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<int> PalletId { get; set; }
        public Nullable<int> PackedProductLotId { get; set; }
        public decimal Quantity { get; set; }
        public int UnitOfMeasureId { get; set; }
    
        public virtual PackedProductLot PackedProductLot { get; set; }
        public virtual Pallet Pallet { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
