//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.RecallTargets = new HashSet<RecallTarget>();
            this.ShipmentItems = new HashSet<ShipmentItem>();
        }
    
        public int ShipmentId { get; set; }
        public System.Guid ShipmentGuid { get; set; }
        public string ShipmentNo { get; set; }
        public int SalesOrderId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public int ShipmentStatusId { get; set; }
        public Nullable<System.DateTime> PlannedLoadAt { get; set; }
        public Nullable<System.DateTime> LoadedAt { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
        public int FromFacilityId { get; set; }
        public string ToAddress { get; set; }
        public Nullable<decimal> TemperatureSetpointC { get; set; }
        public string Notes { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecallTarget> RecallTargets { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual StorageFacility StorageFacility { get; set; }
        public virtual ShipmentStatu ShipmentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItem> ShipmentItems { get; set; }
    }
}
