//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageZone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageZone()
        {
            this.StorageBins = new HashSet<StorageBin>();
            this.StorageConditionLogs = new HashSet<StorageConditionLog>();
        }
    
        public int StorageZoneId { get; set; }
        public System.Guid StorageZoneGuid { get; set; }
        public int StorageFacilityId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TargetTempMinC { get; set; }
        public Nullable<decimal> TargetTempMaxC { get; set; }
        public Nullable<decimal> TargetHumidityMinPct { get; set; }
        public Nullable<decimal> TargetHumidityMaxPct { get; set; }
        public bool IsQuarantineZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageBin> StorageBins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageConditionLog> StorageConditionLogs { get; set; }
        public virtual StorageFacility StorageFacility { get; set; }
    }
}
