//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitsProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageBin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageBin()
        {
            this.InventoryMovements = new HashSet<InventoryMovement>();
            this.InventoryMovements1 = new HashSet<InventoryMovement>();
            this.Pallets = new HashSet<Pallet>();
        }
    
        public int StorageBinId { get; set; }
        public System.Guid StorageBinGuid { get; set; }
        public int StorageZoneId { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMovement> InventoryMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMovement> InventoryMovements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pallet> Pallets { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual StorageZone StorageZone { get; set; }
    }
}
