//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgroInput
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgroInput()
        {
            this.AgroApplications = new HashSet<AgroApplication>();
        }
    
        public int AgroInputId { get; set; }
        public System.Guid AgroInputGuid { get; set; }
        public int AgroInputTypeId { get; set; }
        public string Brand { get; set; }
        public string ProductName { get; set; }
        public string ActiveSubstance { get; set; }
        public string RegistrationNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgroApplication> AgroApplications { get; set; }
        public virtual AgroInputType AgroInputType { get; set; }
    }
}
