//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long AuditLogId { get; set; }
        public System.DateTime OccurredAt { get; set; }
        public string Actor { get; set; }
        public string Action { get; set; }
        public string EntityName { get; set; }
        public string EntityKey { get; set; }
        public string CorrelationId { get; set; }
        public string Details { get; set; }
    }
}
