//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CropCycle()
        {
            this.AgroApplications = new HashSet<AgroApplication>();
            this.HarvestLots = new HashSet<HarvestLot>();
            this.IrrigationEvents = new HashSet<IrrigationEvent>();
        }
    
        public int CropCycleId { get; set; }
        public System.Guid CropCycleGuid { get; set; }
        public int FieldId { get; set; }
        public int ProduceVarietyId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public System.DateTime PlantingDate { get; set; }
        public Nullable<System.DateTime> ExpectedHarvestStart { get; set; }
        public Nullable<System.DateTime> ExpectedHarvestEnd { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgroApplication> AgroApplications { get; set; }
        public virtual Field Field { get; set; }
        public virtual Season Season { get; set; }
        public virtual ProduceVariety ProduceVariety { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HarvestLot> HarvestLots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IrrigationEvent> IrrigationEvents { get; set; }
    }
}
