//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.CropCycles = new HashSet<CropCycle>();
        }
    
        public int FieldId { get; set; }
        public System.Guid FieldGuid { get; set; }
        public int FarmId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal AreaHectares { get; set; }
        public string SoilType { get; set; }
        public bool HasIrrigation { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CropCycle> CropCycles { get; set; }
        public virtual Farm Farm { get; set; }
    }
}
