//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabSample()
        {
            this.LabResults = new HashSet<LabResult>();
        }
    
        public int LabSampleId { get; set; }
        public System.Guid LabSampleGuid { get; set; }
        public int HarvestLotId { get; set; }
        public System.DateTime SampledAt { get; set; }
        public string SampleCode { get; set; }
        public string TakenBy { get; set; }
        public string Notes { get; set; }
    
        public virtual HarvestLot HarvestLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabResult> LabResults { get; set; }
    }
}
