//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackingRun()
        {
            this.PackedProductLots = new HashSet<PackedProductLot>();
        }
    
        public int PackingRunId { get; set; }
        public System.Guid PackingRunGuid { get; set; }
        public string RunCode { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public int FacilityId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackedProductLot> PackedProductLots { get; set; }
        public virtual StorageFacility StorageFacility { get; set; }
    }
}
