//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pallet()
        {
            this.PalletItems = new HashSet<PalletItem>();
            this.RecallTargets = new HashSet<RecallTarget>();
            this.ShipmentItems = new HashSet<ShipmentItem>();
        }
    
        public int PalletId { get; set; }
        public System.Guid PalletGuid { get; set; }
        public string PalletCode { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> StorageBinId { get; set; }
    
        public virtual StorageBin StorageBin { get; set; }
        public virtual StorageFacility StorageFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletItem> PalletItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecallTarget> RecallTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItem> ShipmentItems { get; set; }
    }
}
