//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletItem
    {
        public int PalletItemId { get; set; }
        public int PalletId { get; set; }
        public int PackedProductLotId { get; set; }
        public decimal Quantity { get; set; }
        public int UnitOfMeasureId { get; set; }
    
        public virtual PackedProductLot PackedProductLot { get; set; }
        public virtual Pallet Pallet { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
