//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductionProduceDbEntities : DbContext
    {
        public ProductionProduceDbEntities()
            : base("name=ProductionProduceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgroApplication> AgroApplications { get; set; }
        public virtual DbSet<AgroInput> AgroInputs { get; set; }
        public virtual DbSet<AgroInputType> AgroInputTypes { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CropCycle> CropCycles { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<HarvestLot> HarvestLots { get; set; }
        public virtual DbSet<InspectionType> InspectionTypes { get; set; }
        public virtual DbSet<InventoryMovement> InventoryMovements { get; set; }
        public virtual DbSet<InventoryMovementType> InventoryMovementTypes { get; set; }
        public virtual DbSet<IrrigationEvent> IrrigationEvents { get; set; }
        public virtual DbSet<LabResult> LabResults { get; set; }
        public virtual DbSet<LabResultStatu> LabResultStatus { get; set; }
        public virtual DbSet<LabSample> LabSamples { get; set; }
        public virtual DbSet<LabTestType> LabTestTypes { get; set; }
        public virtual DbSet<LotStatu> LotStatus { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<PackagingType> PackagingTypes { get; set; }
        public virtual DbSet<PackedProductLot> PackedProductLots { get; set; }
        public virtual DbSet<PackingRun> PackingRuns { get; set; }
        public virtual DbSet<Pallet> Pallets { get; set; }
        public virtual DbSet<PalletItem> PalletItems { get; set; }
        public virtual DbSet<ProduceType> ProduceTypes { get; set; }
        public virtual DbSet<ProduceVariety> ProduceVarieties { get; set; }
        public virtual DbSet<QualityGrade> QualityGrades { get; set; }
        public virtual DbSet<QualityInspection> QualityInspections { get; set; }
        public virtual DbSet<Recall> Recalls { get; set; }
        public virtual DbSet<RecallTarget> RecallTargets { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesOrderLine> SalesOrderLines { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<ShipmentItem> ShipmentItems { get; set; }
        public virtual DbSet<ShipmentStatu> ShipmentStatus { get; set; }
        public virtual DbSet<StorageBin> StorageBins { get; set; }
        public virtual DbSet<StorageConditionLog> StorageConditionLogs { get; set; }
        public virtual DbSet<StorageFacility> StorageFacilities { get; set; }
        public virtual DbSet<StorageZone> StorageZones { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
    }
}
