//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityInspection
    {
        public int QualityInspectionId { get; set; }
        public System.Guid QualityInspectionGuid { get; set; }
        public int InspectionTypeId { get; set; }
        public int HarvestLotId { get; set; }
        public System.DateTime InspectedAt { get; set; }
        public string InspectorName { get; set; }
        public Nullable<decimal> TemperatureC { get; set; }
        public string VisualDefectsNotes { get; set; }
        public Nullable<decimal> Brix { get; set; }
        public Nullable<decimal> MoisturePct { get; set; }
        public Nullable<int> ProposedGradeId { get; set; }
        public Nullable<int> ApprovedGradeId { get; set; }
        public bool IsQuarantine { get; set; }
        public string QuarantineReason { get; set; }
    
        public virtual HarvestLot HarvestLot { get; set; }
        public virtual InspectionType InspectionType { get; set; }
        public virtual QualityGrade QualityGrade { get; set; }
        public virtual QualityGrade QualityGrade1 { get; set; }
    }
}
