//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recall()
        {
            this.RecallTargets = new HashSet<RecallTarget>();
        }
    
        public int RecallId { get; set; }
        public System.Guid RecallGuid { get; set; }
        public string RecallCode { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Reason { get; set; }
        public string InitiatedBy { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecallTarget> RecallTargets { get; set; }
    }
}
