//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecallTarget
    {
        public int RecallTargetId { get; set; }
        public int RecallId { get; set; }
        public Nullable<int> HarvestLotId { get; set; }
        public Nullable<int> PackedProductLotId { get; set; }
        public Nullable<int> PalletId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public System.DateTime HoldAppliedAt { get; set; }
        public string HoldReason { get; set; }
    
        public virtual HarvestLot HarvestLot { get; set; }
        public virtual PackedProductLot PackedProductLot { get; set; }
        public virtual Pallet Pallet { get; set; }
        public virtual Recall Recall { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
