//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderLine
    {
        public int SalesOrderLineId { get; set; }
        public int SalesOrderId { get; set; }
        public int ProduceTypeId { get; set; }
        public Nullable<int> ProduceVarietyId { get; set; }
        public Nullable<int> PackagingTypeId { get; set; }
        public Nullable<int> RequestedGradeId { get; set; }
        public decimal Quantity { get; set; }
        public int UnitOfMeasureId { get; set; }
        public string Notes { get; set; }
    
        public virtual PackagingType PackagingType { get; set; }
        public virtual ProduceType ProduceType { get; set; }
        public virtual ProduceVariety ProduceVariety { get; set; }
        public virtual QualityGrade QualityGrade { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
