//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageAllocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageConditionLog
    {
        public int StorageConditionLogId { get; set; }
        public int StorageZoneId { get; set; }
        public System.DateTime LoggedAt { get; set; }
        public Nullable<decimal> TemperatureC { get; set; }
        public Nullable<decimal> HumidityPct { get; set; }
        public Nullable<int> Co2Ppm { get; set; }
        public string Notes { get; set; }
    
        public virtual StorageZone StorageZone { get; set; }
    }
}
